' this file is automatically generated in a pre-build step.  Any manual modifications will be lost.
imports CPP_Classes
Public Class CPP_AlgorithmList
	public Function createCPPAlgorithm(algorithmName as string) as Object
		Return Nothing
	End Function
End Class
