@echo on
copy VB_Classes\RedColor.vb VBClasses\RedColor.vb
copy VB_Classes\LineRGB.vb VBClasses\LineRGB.vb
copy VB_Classes\Contour.vb VBClasses\Contour.vb
copy VB_Classes\EdgeLine.vb VBClasses\EdgeLine.vb
copy VB_Classes\Grid.vb VBClasses\Grid.vb
copy VB_Classes\Brick.vb VBClasses\Brick.vb
copy VB_Classes\Palette.vb VBClasses\Palette.vb
copy VB_Classes\PixelViewer.vb VBClasses\PixelViewer.vb
copy VB_Classes\Pixel.vb VBClasses\Pixel.vb
copy VB_Classes\Filter.vb VBClasses\Filter.vb
copy VB_Classes\OpenGL.vb VBClasses\OpenGL.vb
copy VB_Classes\Gravity.vb VBClasses\Gravity.vb
copy VB_Classes\IMU.vb VBClasses\IMU.vb
copy VB_Classes\Motion.vb VBClasses\Motion.vb
copy VB_Classes\DepthColorizer.vb VBClasses\DepthColorizer.vb
copy VB_Classes\Kalman.vb VBClasses\Kalman.vb
copy VB_Classes\BackProject2d.vb VBClasses\Kalman.vb
copy VB_Classes\BackProject.vb VBClasses\Kalman.vb
copy VB_Classes\BGSubtract.vb VBClasses\Kalman.vb
copy VB_Classes\Bin3Way.vb VBClasses\Kalman.vb
copy VB_Classes\Bin4Way.vb VBClasses\Kalman.vb
copy VB_Classes\BrickPoint.vb VBClasses\Kalman.vb
copy VB_Classes\Brightness.vb VBClasses\Kalman.vb
copy VB_Classes\Kalman.vb VBClasses\Kalman.vb
