// this file is automatically generated in a pre-build step.  Any manual modifications will be lost.
namespace CPP_Classes
{
	public class CPPAlgorithmList
	{
		public CPP_Parent createCPPAlgorithm( string algorithmName )
		{
			if (algorithmName == "AddWeighted_Basics_CPP") return new AddWeighted_Basics_CPP();
			return new AddWeighted_Basics_CPP();
		}
	}
}
