// this file is automatically generated in a pre-build step.  Do not waste your time modifying manually.
using VB_Classes;
using CS_Classes;
namespace CS_Classes
{
	public class CSAlgorithmList
	{
		public CS_Parent createCSAlgorithm( string algorithmName, VB_Classes.VBtask task)
		{
			return new AddWeighted_Basics_CS(task);
		}
	}
}
