// this file is automatically generated in a pre-build step.  Any manual modifications will be lost.
using VB_Classes;
using CS_Classes;
namespace CS_Classes
{
	public class CSAlgorithmList
	{
		public CS_Parent createCSAlgorithm( string algorithmName, VB_Classes.VBtask task)
		{
			if (algorithmName == "CS_BitmapToMat") return new CS_BitmapToMat(task);
			if (algorithmName == "CS_Blob_Basics") return new CS_Blob_Basics(task);
			if (algorithmName == "CS_Blur_Gaussian") return new CS_Blur_Gaussian(task);
			if (algorithmName == "CS_Dither_Basics") return new CS_Dither_Basics(task);
			if (algorithmName == "CS_DNN_Basics") return new CS_DNN_Basics(task);
			if (algorithmName == "CS_DNN_Caffe") return new CS_DNN_Caffe(task);
			if (algorithmName == "CS_DNN_SuperRes") return new CS_DNN_SuperRes(task);
			if (algorithmName == "CS_DNN_Test") return new CS_DNN_Test(task);
			if (algorithmName == "CS_Edge_Motion") return new CS_Edge_Motion(task);
			if (algorithmName == "CS_Edge_NoDepth") return new CS_Edge_NoDepth(task);
			if (algorithmName == "CS_Edge_Sobel") return new CS_Edge_Sobel(task);
			if (algorithmName == "CS_Feature_AKaze") return new CS_Feature_AKaze(task);
			if (algorithmName == "CS_Feature_Kaze") return new CS_Feature_Kaze(task);
			if (algorithmName == "CS_Feature_LeftRight") return new CS_Feature_LeftRight(task);
			if (algorithmName == "CS_Feature_Sample") return new CS_Feature_Sample(task);
			if (algorithmName == "CS_Feature_Sift") return new CS_Feature_Sift(task);
			if (algorithmName == "CS_Feature_SiftSlices") return new CS_Feature_SiftSlices(task);
			if (algorithmName == "CS_Feature_SURF") return new CS_Feature_SURF(task);
			if (algorithmName == "CS_Feature_SURF_Draw") return new CS_Feature_SURF_Draw(task);
			if (algorithmName == "CS_Feature_SURFMatch") return new CS_Feature_SURFMatch(task);
			if (algorithmName == "CS_MeanSubtraction_Basics") return new CS_MeanSubtraction_Basics(task);
			if (algorithmName == "CS_OEX_Sobel_Demo") return new CS_OEX_Sobel_Demo(task);
			if (algorithmName == "CS_OilPaint_Cartoon") return new CS_OilPaint_Cartoon(task);
			if (algorithmName == "CS_OilPaint_Manual") return new CS_OilPaint_Manual(task);
			if (algorithmName == "CS_Sieve_Basics") return new CS_Sieve_Basics(task);
			if (algorithmName == "CS_SLR_Basics") return new CS_SLR_Basics(task);
			if (algorithmName == "CS_SLR_DepthHist") return new CS_SLR_DepthHist(task);
			if (algorithmName == "CS_SLR_Image") return new CS_SLR_Image(task);
			if (algorithmName == "CS_SLR_TrendCompare") return new CS_SLR_TrendCompare(task);
			if (algorithmName == "CS_Voronoi_Basics") return new CS_Voronoi_Basics(task);
			if (algorithmName == "CS_Voronoi_Compare") return new CS_Voronoi_Compare(task);
			if (algorithmName == "CS_Voronoi_CPP") return new CS_Voronoi_CPP(task);
			return new CS_AddWeighted_Basics(task);
		}
	}
}
