Imports OpenCvSharp
Imports OpenCvSharp.Cv2
Imports cv = OpenCvSharp
Namespace VBClasses
    Public Class Hull_Basics : Inherits TaskParent
        Dim redC As New RedC_Basics
        Public Sub New()
            If standalone Then task.gOptions.displayDst1.Checked = True
            desc = "Compare hulls and contours for the redC cells."
        End Sub
        Public Overrides Sub RunAlg(src As cv.Mat)
            redC.Run(src)
            dst2 = redC.dst2
            labels(2) = redC.labels(2)

            Dim rc = task.rcD
            If rc Is Nothing Then rc = redC.rcList(1)
            If rc.contour Is Nothing Then Exit Sub

            dst1.SetTo(0)
            dst3.SetTo(0)

            DrawTour(dst3(rc.rect), rc.contour, task.highlight, task.lineWidth)
            DrawTour(dst1(rc.rect), rc.hull, task.highlight)

            labels(2) = "Contour points count reduced from " + CStr(rc.contour.Count) + " to " + CStr(rc.hull.Count)
        End Sub
    End Class





    Public Class Hull_Edges : Inherits TaskParent
        Dim redC As New RedC_Basics
        Public Sub New()
            desc = "Match hull edges that are also real edges."
        End Sub
        Public Overrides Sub RunAlg(src As cv.Mat)
            redC.Run(src)
            dst2 = redC.dst2
            labels(2) = redC.labels(2)

            CvtColor(task.edges.dst2, dst3, cv.ColorConversionCodes.GRAY2BGR)
            For Each rc In redC.rcList
                DrawTour(dst3(rc.rect), rc.hull, task.highlight, task.lineWidth)
            Next
        End Sub
    End Class






    Public Class XR_Hull_Basics : Inherits TaskParent
        Dim random As New Random_Basics
        Public inputPoints As New List(Of Point2f)
        Public hull As New List(Of cv.Point)
        Public useRandomPoints As Boolean
        Public Sub New()
            labels = {"", "", "Input Points - draw a rectangle anywhere.  Enclosing rectangle in yellow.", ""}
            If standalone Then random.range = New cv.Rect(100, 100, 50, 50)
            desc = "Given a list of points, create a hull that encloses them."
        End Sub
        Private Shared Function vbFloat2Int(ptList2f As List(Of Point2f)) As List(Of cv.Point)
            Dim ptList As New List(Of cv.Point)
            For Each pt In ptList2f
                ptList.Add(New cv.Point(CInt(pt.X), CInt(pt.Y)))
            Next
            Return ptList
        End Function
        Public Overrides Sub RunAlg(src As cv.Mat)
            If (standaloneTest() And task.heartBeat) Or (useRandomPoints And task.heartBeat) Then
                random.Run(src)
                dst2.SetTo(0)
                For Each pt In random.PointList
                    Circle(dst2, pt, task.DotSize, white, -1, task.lineType)
                Next
                inputPoints = New List(Of Point2f)(random.PointList)
            End If
            Dim hull2f = ConvexHull(inputPoints, True)
            hull = vbFloat2Int(hull2f.ToList)
            DrawTour(dst2, hull, Scalar.Yellow)
        End Sub
    End Class






    Public Class XR_Hull_Lines : Inherits TaskParent
        Public hulls As New XR_Contour_Hulls
        Public minDistance As Integer = dst2.Width * 0.02
        Public lpList As New List(Of lpData)
        Public Sub New()
            task.gOptions.DebugSlider.Value = 50
            desc = "Find all the lines generated by XR_Contour_Hulls"
        End Sub
        Public Overrides Sub RunAlg(src As cv.Mat)
            hulls.Run(src)
            dst3 = hulls.dst3
            labels(3) = hulls.labels(3)

            lpList.Clear()
            dst2 = dst3.Clone
            Dim maxLines = task.gOptions.DebugSlider.Value * 2
            For Each contour In hulls.tourList
                Dim ptLast As cv.Point = contour.hull(0)
                For Each pt In contour.hull
                    Dim lp = New lpData(pt, ptLast)
                    If lp.slope >= maxSlope Then Continue For ' likely just the edge of the image.
                    If Math.Abs(lp.slope) < 0.0001 Then Continue For ' likely just the edge of the image

                    lpList.Add(lp)
                    ptLast = pt
                    Line(dst2, lp.p1, lp.p2, task.highlight, task.lineWidth, task.lineType)
                    If lpList.Count >= maxLines Then Exit For
                Next
                If lpList.Count >= maxLines Then Exit For
            Next

            labels(2) = CStr(lpList.Count) + " hull lines"
        End Sub
    End Class






    Public Class XR_HullLine_EdgePoints : Inherits TaskParent
        Dim hullLines As New XR_Hull_Lines
        Public Sub New()
            desc = "Find the edge points for the current and last frm for the hull lines."
        End Sub
        Public Shared Function EdgePointOffset(lpIn As lpData, offset As Integer) As lpData
            Dim lp = New lpData(lpIn.p1, lpIn.p2)
            If lp.ptE1.X <= 1 Then lp.ptE1.X += offset
            If lp.ptE1.Y <= 1 Then lp.ptE1.Y += offset
            If lp.ptE2.X <= 1 Then lp.ptE2.X += offset
            If lp.ptE2.Y <= 1 Then lp.ptE2.Y += offset
            If lp.ptE1.X >= task.workRes.Width - 1 Then lp.ptE1.X -= offset
            If lp.ptE1.Y >= task.workRes.Height - 1 Then lp.ptE1.Y -= offset
            If lp.ptE2.X >= task.workRes.Width - 1 Then lp.ptE2.X -= offset
            If lp.ptE2.Y >= task.workRes.Height - 1 Then lp.ptE2.Y -= offset
            Return lp
        End Function
        Public Overrides Sub RunAlg(src As cv.Mat)
            hullLines.Run(src)
            dst3 = hullLines.dst2
            labels(3) = hullLines.labels(3)

            dst2 = src.Clone
            For Each lpIn In hullLines.lpList
                Dim lp = EdgePointOffset(lpIn, 1)
                Circle(dst2, New cv.Point(CInt(lp.ptE1.X), CInt(lp.ptE1.Y)), task.DotSize, task.highlight, -1, task.lineType)
                Circle(dst2, New cv.Point(CInt(lp.ptE2.X), CInt(lp.ptE2.Y)), task.DotSize, task.highlight, -1, task.lineType)
            Next
            labels(2) = hullLines.labels(2)
        End Sub
    End Class





    Public Class XR_HullLine_SelectHull : Inherits TaskParent
        Dim hullLines As New XR_Hull_Lines
        Public Sub New()
            dst1 = New Mat(dst1.Size, MatType.CV_8U, 0)
            labels(3) = "Click on any hull to see it below with its edge points."
            desc = "Display the contour hull selected."
        End Sub
        Public Overrides Sub RunAlg(src As cv.Mat)
            hullLines.Run(src)

            dst2 = hullLines.dst2
            labels(2) = hullLines.labels(3)

            Dim contour = hullLines.hulls.getSelectedHull()

            dst1.SetTo(0)
            DrawTour(dst1, contour.hull, (contour.ID) Mod 255, -1)
            dst3 = Palettize(dst1, 0)
        End Sub
    End Class




    Public Class XR_Hull_Contour : Inherits TaskParent
        Public hull As New List(Of cv.Point)
        Public contours1 As New Contour_Basics
        Public contours2 As New Contour_Basics
        Public Sub New()
            dst2 = New Mat(dst2.Size, MatType.CV_8U, 0)
            desc = "Compare the hull to the contour of a contour cell"
        End Sub
        Public Overrides Sub RunAlg(src As cv.Mat)
            contours1.Run(src)
            task.contourD = contours1.selectContour()

            dst2.SetTo(0)
            dst2(task.contourD.rect).SetTo(255, task.contourD.mask)
            contours2.Run(dst2)

            dst3.SetTo(0)
            If contours1.sortContours.allContours.Length > 0 Then
                If contours1.sortContours.allContours(0).Length > 0 Then
                    hull = ConvexHull(contours1.sortContours.allContours(0), True).ToList

                    If contours2.sortContours.allContours.Length > 0 Then
                        If contours1.sortContours.allContours(0).Length > 0 Then
                            DrawTour(dst3, contours2.sortContours.allContours(0).ToList, white, -1)
                            DrawTour(dst3, hull, white, task.lineWidth)
                        End If
                    End If
                End If
            End If
        End Sub
    End Class






    Public Class Hull_Defect : Inherits TaskParent
        Public hull As New List(Of cv.Point)
        Public contour As cv.Point()
        Public Sub New()
            desc = "Find defects in the hull provided."
        End Sub
        Public Shared Function indicesMayFail(contour As List(Of cv.Point)) As Boolean
            For i = 0 To contour.Count - 1
                Dim p1 = contour(i)
                For j = i + 1 To contour.Count - 1
                    Dim p2 = contour(j)
                    If p1 = p2 Then Return True
                Next
            Next
            Return False
        End Function
        Public Overrides Sub RunAlg(src As cv.Mat)
            If standalone Then
                Static hContour As New XR_Hull_Contour
                hContour.Run(src)
                dst2 = hContour.dst2
                hull = hContour.hull
                If hContour.contours1.sortContours.allContours.Length = 0 Then Exit Sub ' nothing to work on yet...
                contour = hContour.contours1.sortContours.allContours(0)
            End If

            Dim hullIndices = ConvexHullIndices(contour, False)
            Dim defects = ConvexityDefects(contour, hullIndices.ToList)

            Dim lastV As Integer = -1
            Dim newC As New List(Of cv.Point)
            For Each v In defects
                If v(0) <> lastV And lastV >= 0 Then
                    For i = lastV To v(0) - 1
                        newC.Add(contour(i))
                    Next
                End If
                newC.Add(contour(v(0)))
                newC.Add(contour(v(2)))
                newC.Add(contour(v(1)))
                lastV = v(1)
            Next
            dst3.SetTo(0)
            DrawTour(dst3, newC, white)
        End Sub
    End Class




    Public Class Hull_Contour : Inherits TaskParent
        Dim redC As New RedC_Basics
        Public Sub New()
            If standalone Then task.gOptions.displayDst1.Checked = True
            labels(1) = "Contour is in white and hull is highlighted."
            desc = "Compare the hull to the contour of a contour cell"
        End Sub
        Public Overrides Sub RunAlg(src As cv.Mat)
            redC.Run(src)
            dst2 = redC.dst2
            labels(2) = redC.labels(2)

            Dim rc = task.rcD
            If rc Is Nothing Then rc = redC.rcList(1)

            Dim newSize = New cv.Size(rc.rect.Width, rc.rect.Width * dst2.Height / dst2.Width)
            If rc.rect.Width * dst2.Height / dst2.Width Then
                newSize = New cv.Size(rc.rect.Height * dst2.Width / dst2.Height, rc.rect.Height)
            End If
            Dim tmp As New cv.Mat(newSize, cv.MatType.CV_8UC3, 0)
            DrawTour(tmp, rc.contour, white, task.lineWidth)
            DrawTour(tmp, rc.hull, task.highlight, task.lineWidth)
            Resize(tmp, dst1, dst1.Size, 0, 0, cv.InterpolationFlags.Nearest)

            Dim hullIndices = ConvexHullIndices(rc.contour, False)
            If Hull_Defect.indicesMayFail(rc.contour) Then Exit Sub

            Dim defects = ConvexityDefects(rc.contour, hullIndices.ToList)

            Dim lastV As Integer = -1
            Dim tour As New List(Of cv.Point)
            For Each v In defects
                If v(0) <> lastV And lastV >= 0 Then
                    For i = lastV To v(0) - 1
                        tour.Add(rc.contour(i))
                    Next
                End If
                tour.Add(rc.contour(v(0)))
                tour.Add(rc.contour(v(2)))
                tour.Add(rc.contour(v(1)))
                lastV = v(1)
            Next

            dst3.SetTo(0)
            DrawTour(dst3(rc.rect), rc.contour, white, task.lineWidth)
            DrawTour(dst3(rc.rect), tour, task.highlight, task.lineWidth)
        End Sub
    End Class
End Namespace
