Imports System.IO
Imports System.Threading

Module Program
    Sub Main()
        ' Ensure only one instance can run at a time using a named Mutex
        Dim mutexName As String = "Global\UI_Generator_SingleInstance"
        Dim createdNew As Boolean = False

        Using mutex As New Mutex(True, mutexName, createdNew)
            If Not createdNew Then
                Console.WriteLine("Another instance of UI_Generator is already running.")
                Return
            End If

            ' Use relative path from the executable's location
            Dim appPath As String = AppDomain.CurrentDomain.BaseDirectory
            Dim vbClassesPath As String = Path.GetFullPath(Path.Combine(appPath, "..\..\..\..\..\VBClasses"))
            Dim vbClasses As New SortedList(Of String, String)
            Dim xrClasses As New SortedList(Of String, String)
            Dim cursorClasses As New SortedList(Of String, String)
            Dim displayClasses As New SortedList(Of String, String)
            Dim allClasses As New SortedList(Of String, String)
            Dim totalLinesRead As Integer

            ' Get all .vb files in the VBClasses directory
            Dim vbFiles() As String = Directory.GetFiles(vbClassesPath, "*.vb")

            Dim toggleTotal As Integer
            Dim currClassname As String = ""
            Dim charQ As Char = "'"
            For Each vbFile As String In vbFiles
                Dim lines() As String = File.ReadAllLines(vbFile)

                For Each line As String In lines
                    Dim trimmedLine As String = line.Trim()
                    If trimmedLine.StartsWith(charQ) Then Continue For

                    ' Count non-empty, non-comment lines
                    If Not String.IsNullOrEmpty(trimmedLine) Then If toggleTotal Then totalLinesRead += 1

                    If currClassname <> "" Then
                        Dim testLine = trimmedLine.ToLower
                        If testLine.Contains("cursor.ai") Then cursorClasses.Add(currClassname, currClassname)
                    End If
                    If trimmedLine.Contains(": Inherits TaskParent") Then
                        toggleTotal = False
                        ' Parse the class name from lines like: "Public Class ClassName : Inherits " + parentName
                        currClassname = ExtractClassName(trimmedLine)
                        If Not String.IsNullOrEmpty(currClassname) Then
                            allClasses.Add(currClassname, currClassname)
                            If currClassname.StartsWith("XR_") Then
                                xrClasses.Add(currClassname, currClassname)

                                ' comment both of these lines to remove XR_ algorithms.
                                'displayClasses.Add(currClassname, currClassname)
                                'toggleTotal = True
                            ElseIf currClassname.StartsWith("XO_") Then
                                ' skipping it now...
                            Else
                                vbClasses.Add(currClassname, currClassname)
                                displayClasses.Add(currClassname, currClassname)
                                toggleTotal = True
                            End If
                        End If
                    End If
                Next
            Next

            ' Write the counts to AlgorithmCounts.txt
            Dim dataPath As String = Path.GetFullPath(Path.Combine(appPath, "..\..\..\..\..\Data"))
            Dim countsFilePath As String = Path.Combine(dataPath, "AlgorithmCounts.txt")
            Dim countsContent As String = "CodeLineCount = " & totalLinesRead.ToString() & vbCrLf &
                                          "AlgorithmCount = " & displayClasses.Count.ToString() & vbCrLf &
                                          "Reference algorithm count = " & vbCrLf &
                                          "Average lines for displayed algorithm = " &
                                          (totalLinesRead \ displayClasses.Count).ToString() & vbCrLf
            File.WriteAllText(countsFilePath, countsContent)

            ' Generate AlgorithmList.vb in the Main directory
            Dim sb As New System.Text.StringBuilder()

            sb.AppendLine("' this file is automatically generated in a pre-build step.  Any manual modifications will be lost.")
            sb.AppendLine("Imports VBClasses")
            sb.AppendLine("Imports PixelViewer")
            sb.AppendLine("Namespace MainApp")

            sb.AppendLine("Partial Public Class MainUI")

            sb.AppendLine(vbTab + "Public Function CreateAlgorithm(algorithmName as string) As TaskParent")

            For Each className As String In displayClasses.Keys
                sb.AppendLine($"If algorithmName = ""{className}"" Then Return New {className}")
            Next
            sb.AppendLine(vbTab + vbTab + "Return Nothing")
            sb.AppendLine(vbTab + "End Function")
            sb.AppendLine("End Class")
            sb.AppendLine("End NameSpace")

            Dim mainPath As String = Path.GetFullPath(Path.Combine(appPath, "..\..\..\..\..\MainUI"))
            Dim algorithmListPath As String = Path.Combine(mainPath, "AlgorithmList.vb")

            File.WriteAllText(algorithmListPath, sb.ToString())

            ' Extract first tokens from class names and write to GroupButtons.txt
            Dim groupTokens As New SortedList(Of String, String)
            For Each className As String In displayClasses.Keys
                Dim parts() As String = className.Split("_"c)
                If parts.Length > 0 And Not String.IsNullOrEmpty(parts(0)) Then
                    If Not groupTokens.ContainsKey(parts(0)) Then
                        groupTokens.Add(parts(0), parts(0))
                    End If
                End If
            Next

            Dim groupButtonsPath As String = Path.Combine(dataPath, "GroupButtonList.txt")
            Dim groupSb As New System.Text.StringBuilder()
            For Each token As String In groupTokens.Keys
                groupSb.AppendLine(token)
            Next
            File.WriteAllText(groupButtonsPath, groupSb.ToString())

            Dim AvailableAlgorithmsPath As String = Path.Combine(dataPath, "AvailableAlgorithms.txt")
            Dim algList As New System.Text.StringBuilder()
            For Each token As String In displayClasses.Keys
                algList.AppendLine(token)
            Next
            File.WriteAllText(AvailableAlgorithmsPath, algList.ToString())

            Console.WriteLine()
            Console.WriteLine()
            Console.WriteLine($"{displayClasses.Count} classes will be displayed:")
            Console.WriteLine($"Total source lines for displayed classes: {totalLinesRead}")
            Console.WriteLine($"XR_ Reference algorithm count: {xrClasses.Count}")
            Console.WriteLine($"Cursor.ai algorithms: {cursorClasses.Count}")
            Console.WriteLine($"Total algorithms in development: { allClasses.Count}")
            Console.WriteLine($"Average lines per displayed algorithm: " + (totalLinesRead \ displayClasses.Count).ToString())
            Console.WriteLine($"Algorithm groups: {groupTokens.Count}")
            Console.WriteLine()
            Console.WriteLine()
        End Using
    End Sub

    Function ExtractClassName(line As String) As String
        ' Line format: "Public Class ClassName : Inherits TaskParent"
        ' Find "Class " and ": Inherits"
        Dim classIndex As Integer = line.IndexOf("Class ")
        Dim inheritsIndex As Integer = line.IndexOf(": Inherits")

        If classIndex >= 0 And inheritsIndex > classIndex Then
            Dim startPos As Integer = classIndex + 6  ' Length of "Class "
            Dim className As String = line.Substring(startPos, inheritsIndex - startPos).Trim()
            Return className
        End If

        Return Nothing
    End Function
End Module
